pull_request_rules:
  - name: bbp test label
    conditions:
      - base = main
    actions:
      label:
        add: ["bbp-test"]
  - name: t22 queue
    conditions:
      - base = main
      - label = bbp-queue
    actions:
      queue:
        name: bbp22
queue_rules:
  - name: bbp22
    checks_timeout: 10 minutes
    merge_conditions:
      - check-success = bbp-q22
